services:
  management-api:
    image: restaurant-management-api:latest
    container_name: restaurant-management-api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://160.191.245.32:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: vuducbo
      SPRING_DATASOURCE_PASSWORD: Duc17052003*
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped

  # Portal API
  portal-api:
    image: restaurant-portal-api:latest
    container_name: restaurant-portal-api
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://160.191.245.32:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: vuducbo
      SPRING_DATASOURCE_PASSWORD: Duc17052003*
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped
